sudo: false
language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script: yarn test:ci

after_success: yarn build:website
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DEPLOY_TOKEN
  local_dir: website/dist
  on:
    branch: master
    node: "10"
