[build]
command = "yarn build"
#ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ../react-docgen/"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ."
publish = ".next"

[environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
