name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

permissions: {}

env:
  NODE_VERSION: 18

jobs:
  tests:
    strategy:
      matrix:
        node: ['14.17.0', '16', '18']
        os: ['ubuntu']
        include:
          - os: macos
            node: '18'
          - os: windows
            node: '18'

    name: Tests (Node.js v${{ matrix.node }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Unit tests with coverage
        if: '${{ matrix.node == env.NODE_VERSION }}'
        run: yarn test --coverage

      - name: Unit tests
        if: '${{ matrix.node != env.NODE_VERSION }}'
        run: yarn test

      - name: Upload coverage to Codecov
        if: '${{ matrix.node == env.NODE_VERSION }}'
        uses: codecov/codecov-action@v3

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

  website:
    name: Test build website
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Build website
        run: yarn website:build

  deploy:
    name: Deploy website
    permissions:
      contents: write
    needs: [tests, lint]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Build website
        run: yarn website:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: website/dist
