
name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

env:
  NODE_VERSION: 16

jobs:
  tests:
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Unit tests (Node v${{ matrix.node }})
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'

    - name: Cache node_modules
      uses: actions/cache@v2
      id: cache-nodemodules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive

    - name: Unit tests
      run: yarn test --ci

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Cache node_modules
      uses: actions/cache@v2
      id: cache-nodemodules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive

    - name: Install website dependencies
      run: yarn install --frozen-lockfile --non-interactive
      working-directory: ./website

    - name: Lint
      run: yarn lint

  website:
    name: Test build website
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Cache node_modules
      uses: actions/cache@v2
      id: cache-nodemodules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive

    - name: Install website dependencies
      run: yarn install --frozen-lockfile --non-interactive
      working-directory: ./website

    - name: Build website
      run: yarn build
      working-directory: ./website

  deploy:
    name: Deploy website
    needs: [tests, lint]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Cache node_modules
      uses: actions/cache@v2
      id: cache-nodemodules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive

    - name: Install website dependencies
      run: yarn install --frozen-lockfile --non-interactive
      working-directory: ./website

    - name: Build
      run: yarn build
      working-directory: ./website

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: website/dist
