on:
  push:
    branches:
      - main
name: release-please
env:
  NODE_VERSION: 18
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      pr: ${{ steps.release.outputs.pr }}
      'packages/react-docgen--release_created': ${{ steps.release.outputs['packages/react-docgen--release_created'] }}
      'packages/react-docgen-cli--release_created': ${{ steps.release.outputs['packages/react-docgen-cli--release_created'] }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

  update-lock:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.pr && !needs.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release-please--branches--main
          fetch-depth: 2
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Update yarn lock
        run: yarn install --mode=update-lockfile

      - name: Committing and push changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add yarn.lock
          git commit --amend --no-edit
          git push --force

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - run: yarn npm publish --tag=next --access=public
        working-directory: packages/react-docgen
        if: ${{ needs.release.outputs['packages/react-docgen--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: yarn npm publish --tag=next --access=public
        working-directory: packages/react-docgen-cli
        if: ${{ needs.release.outputs['packages/react-docgen-cli--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
