on:
  push:
    branches:
      - main
name: release-please
env:
  NODE_VERSION: 18
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - name: Setup Node.js
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: yarn install --immutable

      - name: Build package
        if: ${{ steps.release.outputs.releases_created }}
        run: yarn build

      - run: npm publish packages/react-docgen/ --tag=next --access=public
        if: ${{ steps.release.outputs['packages/react-docgen--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm publish packages/react-docgen-cli/ --tag=next --access=public
        if: ${{ steps.release.outputs['packages/react-docgen-cli--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
